### ISSUE TITLE
TPB06: Tirar o link para whatsapp privado de uma das fundadoras da versão mobile

### ISSUE THREAD

**Issue by guizg** [tech-pro-bem/saude-da-rua-frontend#142]
Vi que [nesse commit](https://github.com/tech-pro-bem/saude-da-rua-frontend/commit/a30aa1210d1e2d150189d8c15eeadbe24f6feec2), de 2 semanas atrás, foi tirado o link para o whatsapp pessoal de uma das fundadoras na versão web.
Sou primo dela, ela me pediu para que tirasse da versão mobile também. 
Vi que está [nesse arquivo](https://github.com/tech-pro-bem/saude-da-rua-frontend/blob/b76e27357318dba7868efc98e910eba846264fbb/src/components/SocialMedia/mobile/SocialMediaMobile.jsx), mas não consegui abrir dar push numa branch nova com essa mudança, me deu falta de permissão...
Podem me dar permissão ou alguém fazer essa mudança, por favor?

**Comment by lucas-lm** [comment]
Obrigado pela observação @guizg !
Acabei de remover no último commit. 

Caso tenha alguma outra contribuição futura, pode fazer um fork do repositório e abrir um PR do seu fork pra esse repositório! Valeu!
